### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by zeroxd0d0e0a0d0b0e0e0f** [joepie91/todo#1]
@joepie91 sup man

Is it possible to create a Dockerfile for this project? Having troubles getting this to run in 2021.

**Comment by zeroxd0d0e0a0d0b0e0e0f** [comment]
Dockerfile

```
# PHP Version
FROM php:7.3-apache

# Install the PHP extensions we need
RUN apt-get update && \
apt-get install -y --no-install-recommends \
    curl \
    libmemcached-dev \
    libzip-dev \
    libz-dev \
    libpq-dev \
    libjpeg-dev \
    libpng-dev \
    libfreetype6-dev \
    libicu-dev \
    libssl-dev \
    libmcrypt-dev \
    zlib1g-dev && \
    docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr && \
    docker-php-ext-install gd mysqli opcache intl zip

# Install Memcached
RUN pecl install memcached-3.1.5 && \
    docker-php-ext-enable memcached
```

docker-compose.yml

```
version: "3.8"
services:
  php:
    build: .
    networks:
      - backend
    volumes:
      - ./config.json:/var/www/config.json
      - ./cphp:/var/www/cphp
      - ./public_html:/var/www/html
    depends_on:
      - mysql
      - memcached
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
  mysql:
    image: mysql:8.0
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todo
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
        - "11211:11211"
    networks:
      - backend
networks:
  frontend:
  backend:
```
